// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"EasyTime/internal/dao/internal"
)

// internalClaNotesDao is internal type for wrapping internal DAO implements.
type internalClaNotesDao = *internal.ClaNotesDao

// claNotesDao is the data access object for table Cla_Notes.
// You can define custom methods on it to extend its functionality as you wish.
type claNotesDao struct {
	internalClaNotesDao
}

var (
	// ClaNotes is globally public accessible object for table Cla_Notes operations.
	ClaNotes = claNotesDao{
		internal.NewClaNotesDao(),
	}
)

// Fill with you ideas below.
