// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure for table user.
type User struct {
	Id         int         `json:"id"         ` // User ID
	Nickname   string      `json:"nickname"   ` // User Nickname
	Password   string      `json:"password"   ` // User Passport
	CreateTime *gtime.Time `json:"createTime" ` // Created Time
	Phone      string      `json:"phone"      ` // User Phone
	Ext        string      `json:"ext"        ` // ext
	Passport   string      `json:"passport"   ` // passport
	Updatetime *gtime.Time `json:"updatetime" ` //
}
