// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// ClaNotesDao is the data access object for table Cla_Notes.
type ClaNotesDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns ClaNotesColumns // columns contains all the column names of Table for convenient usage.
}

// ClaNotesColumns defines and stores column names for table Cla_Notes.
type ClaNotesColumns struct {
	Date  string // 日期
	Group string // 分组
	Desc  string // 描述
	Id    string // ID
}

// claNotesColumns holds the columns for table Cla_Notes.
var claNotesColumns = ClaNotesColumns{
	Date:  "Date",
	Group: "Group",
	Desc:  "Desc",
	Id:    "Id",
}

// NewClaNotesDao creates and returns a new DAO object for table data access.
func NewClaNotesDao() *ClaNotesDao {
	return &ClaNotesDao{
		group:   "default",
		table:   "Cla_Notes",
		columns: claNotesColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *ClaNotesDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *ClaNotesDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *ClaNotesDao) Columns() ClaNotesColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *ClaNotesDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *ClaNotesDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *ClaNotesDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
