// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"ProjectRoot/internal/model"
	"context"
)

type (
	ICalendarNotes interface {
		AddNotes(ctx context.Context, in model.CalendarNotesAddInput)
		DelNotes(ctx context.Context, in model.CalendarNotesDelImput)
		ModifyNotes(ctx context.Context, in model.CalendarNotesModifyInput)
	}
)

var (
	localCalendarNotes ICalendarNotes
)

func CalendarNotes() ICalendarNotes {
	if localCalendarNotes == nil {
		panic("implement not found for interface ICalendarNotes, forgot register?")
	}
	return localCalendarNotes
}

func RegisterCalendarNotes(i ICalendarNotes) {
	localCalendarNotes = i
}
