// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// User is the golang structure of table user for DAO operations like Where/Data.
type User struct {
	g.Meta     `orm:"table:user, do:true"`
	Id         interface{} // User ID
	Nickname   interface{} // User Nickname
	Password   interface{} // User Passport
	CreateTime *gtime.Time // Created Time
	Phone      interface{} // User Phone
	Ext        interface{} //
}
